#!/bin/bash
inputFile=$1
if [ $# -ne 1 ]
then
	echo "Usage: $0 option"
else
	MYPATH=/opt/bitnami/apache2/htdocs/php
	> $MYPATH/errors.txt
	> $MYPATH/output.txt
	fileName=$(basename $inputFile .txt).cs
	cp $inputFile $fileName
	exeName=$(basename $inputFile .txt).exe
	mcs $fileName 1> $MYPATH/errors.txt
	if [ -s $MYPATH/errors.txt ]
	then
		echo "Encountered Errors"
	else
		echo "Comiled correctly"
		mono $exeName 1> $MYPATH/output.txt
	fi
	rm $exeName
	rm $fileName
fi
